# Generated by Django 5.2.4 on 2025-08-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="post.postattachment"),
        ),
    ]
